/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vos_CONSTANTS_H
#define vos_CONSTANTS_H

#include "vos_types.h"



class vosConstants {
 public:
  vosConstants();

};

extern const vosConstants g_vos_constants;



#endif
