/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "VOSServer.h"




VOSServer_SendOrderInfo_args::~VOSServer_SendOrderInfo_args() throw() {
}


uint32_t VOSServer_SendOrderInfo_args::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->oi.read(iprot);
          this->__isset.oi = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t VOSServer_SendOrderInfo_args::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("VOSServer_SendOrderInfo_args");

  xfer += oprot->writeFieldBegin("oi", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->oi.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}


VOSServer_SendOrderInfo_pargs::~VOSServer_SendOrderInfo_pargs() throw() {
}


uint32_t VOSServer_SendOrderInfo_pargs::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("VOSServer_SendOrderInfo_pargs");

  xfer += oprot->writeFieldBegin("oi", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += (*(this->oi)).write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void VOSServerClient::SendOrderInfo(const OrderInfo& oi)
{
  send_SendOrderInfo(oi);
}

void VOSServerClient::send_SendOrderInfo(const OrderInfo& oi)
{
  int32_t cseqid = 0;
  oprot_->writeMessageBegin("SendOrderInfo", ::apache::thrift::protocol::T_ONEWAY, cseqid);

  VOSServer_SendOrderInfo_pargs args;
  args.oi = &oi;
  args.write(oprot_);

  oprot_->writeMessageEnd();
  oprot_->getTransport()->writeEnd();
  oprot_->getTransport()->flush();
}

bool VOSServerProcessor::dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) {
  ProcessMap::iterator pfn;
  pfn = processMap_.find(fname);
  if (pfn == processMap_.end()) {
    iprot->skip(::apache::thrift::protocol::T_STRUCT);
    iprot->readMessageEnd();
    iprot->getTransport()->readEnd();
    ::apache::thrift::TApplicationException x(::apache::thrift::TApplicationException::UNKNOWN_METHOD, "Invalid method name: '"+fname+"'");
    oprot->writeMessageBegin(fname, ::apache::thrift::protocol::T_EXCEPTION, seqid);
    x.write(oprot);
    oprot->writeMessageEnd();
    oprot->getTransport()->writeEnd();
    oprot->getTransport()->flush();
    return true;
  }
  (this->*(pfn->second))(seqid, iprot, oprot, callContext);
  return true;
}

void VOSServerProcessor::process_SendOrderInfo(int32_t, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol*, void* callContext)
{
  void* ctx = NULL;
  if (this->eventHandler_.get() != NULL) {
    ctx = this->eventHandler_->getContext("VOSServer.SendOrderInfo", callContext);
  }
  ::apache::thrift::TProcessorContextFreer freer(this->eventHandler_.get(), ctx, "VOSServer.SendOrderInfo");

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->preRead(ctx, "VOSServer.SendOrderInfo");
  }

  VOSServer_SendOrderInfo_args args;
  args.read(iprot);
  iprot->readMessageEnd();
  uint32_t bytes = iprot->getTransport()->readEnd();

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->postRead(ctx, "VOSServer.SendOrderInfo", bytes);
  }

  try {
    iface_->SendOrderInfo(args.oi);
  } catch (const std::exception&) {
    if (this->eventHandler_.get() != NULL) {
      this->eventHandler_->handlerError(ctx, "VOSServer.SendOrderInfo");
    }
    return;
  }

  if (this->eventHandler_.get() != NULL) {
    this->eventHandler_->asyncComplete(ctx, "VOSServer.SendOrderInfo");
  }

  return;
}

::boost::shared_ptr< ::apache::thrift::TProcessor > VOSServerProcessorFactory::getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) {
  ::apache::thrift::ReleaseHandler< VOSServerIfFactory > cleanup(handlerFactory_);
  ::boost::shared_ptr< VOSServerIf > handler(handlerFactory_->getHandler(connInfo), cleanup);
  ::boost::shared_ptr< ::apache::thrift::TProcessor > processor(new VOSServerProcessor(handler));
  return processor;
}

void VOSServerConcurrentClient::SendOrderInfo(const OrderInfo& oi)
{
  send_SendOrderInfo(oi);
}

void VOSServerConcurrentClient::send_SendOrderInfo(const OrderInfo& oi)
{
  int32_t cseqid = 0;
  ::apache::thrift::async::TConcurrentSendSentry sentry(&this->sync_);
  oprot_->writeMessageBegin("SendOrderInfo", ::apache::thrift::protocol::T_ONEWAY, cseqid);

  VOSServer_SendOrderInfo_pargs args;
  args.oi = &oi;
  args.write(oprot_);

  oprot_->writeMessageEnd();
  oprot_->getTransport()->writeEnd();
  oprot_->getTransport()->flush();

  sentry.commit();
}



